[package]
name = "attn_notifier"
version = "0.1.0"
edition = "2021"

[dependencies]
attn_client = { path = "../attn_client" }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
reqwest = { workspace = true }
