[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
stable_vault = "FnQ56fWaHuKZ3p1Jvr8TVf6aCr5SEstvjoo5cZQ5WQTz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/stable_vault"]

[scripts]
test = "anchor test"
