[package]
name = "attn_api"
version = "0.1.0"
edition = "2021"

[dependencies]
attn_indexer = { path = "../attn_indexer", optional = true }
axum = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
